FROM unrealcv/base
# tzdata is required, otherwise will have /etc/localtime not found error
RUN sudo apt-get install -y tzdata
ADD UnrealEngine414 /home/unrealcv/UnrealEngine414
WORKDIR /home/unrealcv/UnrealEngine414
# RUN sudo ./Setup.sh
# RUN ./GenerateProjectFiles.sh
